FROM node:18-alpine

# Create app directory

WORKDIR /src/backend

# Install app dependencies

COPY package*.json ./


RUN npm ci

# Bundel app source

COPY . .

EXPOSE 6000

CMD [ "npm","run","dev" ]